# Generated by Django 4.2.17 on 2025-02-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
    ]
