# Generated by Django 4.2.17 on 2025-02-12 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_class_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='cteacher',
            new_name='teacher',
        ),
    ]
