# Generated by Django 4.2.17 on 2025-02-12 06:40

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_cteacher_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='course',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(20)], verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='student',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(100)], verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.CharField(choices=[('', '请选择性别'), ('male', '男'), ('female', '女')], max_length=10, verbose_name='性别'),
        ),
    ]
