# Generated by Django 4.2.17 on 2025-02-12 07:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_class_remarks_alter_course_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='remarks',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='备注'),
        ),
    ]
